/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.util.ArrayList;

import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import searching.PatternFinder;
import utilities.Tools;

/**
 *
 * @author Dan
 */
public class PatternsUI extends javax.swing.JFrame implements
		ListSelectionListener {

	DefaultListModel patterns = new DefaultListModel();

	/**
	 * Creates new form PatternsUI
	 */
	public PatternsUI(ArrayList<ArrayList<String>> patterns) {
		initComponents();
		for (ArrayList<String> a : patterns) {
			this.patterns
					.addElement("------------------------------------------");
			for (String s : a) {
				this.patterns.addElement(s);
			}
		}
		PATTERNLIST.setModel(this.patterns);
		PATTERNLIST.addListSelectionListener(this);
		this.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		PATTERNLIST = new javax.swing.JList();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jScrollPane1.setViewportView(PATTERNLIST);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 602,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 529,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	// Variables declaration - do not modify
	private javax.swing.JList PATTERNLIST;
	private javax.swing.JScrollPane jScrollPane1;

	// End of variables declaration

	@Override
	public void valueChanged(ListSelectionEvent e) {
		if (PATTERNLIST.getSelectedValue() != null) {
			String text = "";
			for (Object o : PATTERNLIST.getSelectedValues()) {
				String current = o.toString();
				if (PatternFinder.isFieldInsn(current)
						|| current.contains("if_")
						|| current.contains("invoke")
						|| current.contains("ifeq"))
					current = Tools.getFirstword(current);
				text += " \""
						+ current
								.replace(
										"      #######################################################",
										"") + "\",";
			}
			// Tools.log("Copied: " + text + " to clipboard!");
			StringSelection stringSelection = new StringSelection(text);
			Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
			clpbrd.setContents(stringSelection, null);
		}
	}
}
